join_timeout: 10
co_time: 10
timeout: 10
logfile: /tmp/vault.log

vault:
  - init: true
    name: 'node1'
    auto-unsealing: true
    init-payload: { "secret_shares": 5, "secret_threshold": 3 }
    path: '/v1'
    address: http://127.0.0.1:8200

  - init: false
    name: 'node2'
    auto-unsealing: true
    init-payload: { "secret_shares": 5, "secret_threshold": 3 }
    path: '/v1'
    address: http://127.0.0.1:8200

consul:
  address: http://consulmod:8500
  path: /v1/kv
  acl-token: 'very-secret-token'

secrets:
  aes: "4NHSl6fvvessx2d="
  iv: "6NgEl6fkjessx2d="

#Only needed if your cluster it has been already initialized
shamir_keys: []
root_token: ''
