FROM centos:7

COPY vault /usr/bin/vault
COPY vault.hcl /etc/vault.hcl
RUN yum install nano epel-release -y && \
	yum install python2-pip nano -y && \
	pip install requests pyYAML
CMD ["vault", "server", "-config=/etc/vault.hcl"]